Robot@<addr0>
Pos: (42.5;0) Speed: (0;0)
Laps: 0 Alive: true
Robot@<addr1>
Pos: (45;0) Speed: (0;0)
Laps: 0 Alive: true
Robot@<addr2>
Pos: (47.5;0) Speed: (0;0)
Laps: 0 Alive: true
Robot@<addr0>
Pos: (43.5;0) Speed: (1;0)
Laps: 0 Alive: true
Robot@<addr1>
Pos: (46;0) Speed: (1;0)
Laps: 0 Alive: true
Robot@<addr2>
Pos: (48.5;0) Speed: (1;0)
Laps: 0 Alive: true
Robot@<addr0>
Pos: (44.5;0) Speed: (2;0)
Laps: 0 Alive: true